### ISSUE TITLE
Forwarding messages from source chat to admin chat bans author of the message

### ISSUE THREAD

**Issue by marinegor** [umputun/tg-spam#118]
Pretty much as described in the title: if we (=someone who is configured as super user of the bot) forward any (not only first) message from the source chat to the admin chat, the author of this message gets banned in the original moderated chat. We also don't get a normal notification from the bot (with the unban button), so we have to
go to the admin panel and unban manually.

Ia this a bug, or there's a feature flag to disable it?

PS: I'm happy to share logs (in debug mode) in private, if needed

**Comment by coperius** [comment]
I think sending a direct report implies that the superuser has already determined that it is a spam message.  It is also very likely that the superuser will also be a member of the admin group. Superusers are not just able to send reports, but are full-fledged moderators and can ban users with the bot without being admins

**Comment by marinegor** [comment]
>I think sending a direct report implies that the superuser has already determined that it is a spam message. 

Not always -- sometimes we forward messages with comments regarding what to do with the sender's request in private. And if we want to ban someone, we can do it in the source (i.e. moderated) chat via sending `/spam` command.

In short, I want to be able to forward messages to the admin chat without any consequences for the user who sent this message :)

**Comment by umputun** [comment]
this is not how it is supposed to work, sounds like a bug to me. I don't see anything like this in my groups.

Having a log around this even will help to hunt it down. If you don't want to publish it here, feel free to send to my tg (umputun) or email. if you send a fragment of the log, pls also send the start of it, where things are loaded and initialized.

**Comment by umputun** [comment]
I think I misread your report. I thought it was trying to ban the admin who forwarded the message, but from what I see in your log, it bans the author of the forwarded messages. If this is the case, then it works as designed. Forwarding to the admin group is the same as replying with the /spam command.

**Comment by umputun** [comment]
however, this system has a parameter to disable this behavior:

```	
DisableAdminSpamForward bool   `long:"disable-admin-spam-forward" env:"DISABLE_ADMIN_SPAM_FORWARD" description:"disable forwarding spam messages to admin group"`
```

If you set it, forwarding won't trigger the ban.
