### ISSUE TITLE
Do not remove users after unban

### ISSUE THREAD

**Issue by slawiko** [umputun/tg-spam#12]
According to [docs](https://core.telegram.org/bots/api#unbanchatmember) 

> By default, this method guarantees that after the call the user is not a member of the chat, but will be able to join it. So if the user is a member of the chat they will also be removed from the chat

In my use case I would like to avoid it. In order to do it the `only_if_banned` parameter has to be passed. I would like to add it.

I will do it if you are ok with it. Do you think it should be run parameter, or it's fine to make it only possible behaviour of tg-spam?

**Comment by umputun** [comment]
I need help understanding the issue. What exactly you are trying to avoid and why? I don't see how `only_if_banned` will affect anything - the moment you see this message in the admin chat user is already banned

**Comment by slawiko** [comment]
When I unban user, I want him to stay in the group (which is not default behaviour according to [docs](https://core.telegram.org/bots/api#unbanchatmember)). It can be achieved only by passing `only_if_banned` parameter to the unban API

**Comment by umputun** [comment]
hmm, no, this is not what I witnessed. The moment I unban a user I see him re-joining the group automatically. I mean this is how it currently working, without any special flags passed in

**Comment by slawiko** [comment]
Interesting, because not only I observe it, but it is even written in docs

> The user will not return to the group or channel automatically

probably it has something with my groups settings, same as https://github.com/umputun/tg-spam/pull/4

Anyway feel free to close if you do not want to have it. I will do it in my fork just in case

**Comment by umputun** [comment]
i don't mind. but make sure you document it and explain what is the use case

**Comment by slawiko** [comment]
Fixed in [v1.3.0](https://github.com/umputun/tg-spam/releases/tag/v1.3.0)
