### ISSUE TITLE
Disabling the "admin forwarding msg to admin channel -> ban" feature

### ISSUE THREAD

**Issue by DarthGandalf** [umputun/tg-spam#123]
There are reasons to forward messages to admin channel other than to tell the bot to ban the user. And if the ban is what's needed, `/spam` command is enough.

This feature will lead to accidental bans of innocent people.

But also it's buggy and shows errors like `error: not found "" in locator` when the source of the message is not in the moderated channel, but elsewhere. Also note the "" in it: if someone posts a picture in the channel, but then one of admins forwards another unrelated picture from someone else, will that first user be banned for posting a picture? Since the hash of an empty string "" is the same.

The only way I see how to disable this (other than editing source code) is to disable admin group, but the feature of admin group is still useful as the admin-visible log of whom the bot banned, to make it easy to unban them.

**Comment by DarthGandalf** [comment]
Hm, from reading source, `DisableAdminSpamForward` may actually do what I want.

The issue is with the description of this option - it sounds that it disables the feature of the bot itself forwarding spam message TO the admin channel

**Comment by umputun** [comment]
If you can improve the docs to make them clearer and more readable, please provide a PR.
