### ISSUE TITLE
Make it possible to see Info after unban

### ISSUE THREAD

**Issue by DarthGandalf** [umputun/tg-spam#125]
![Выделение_613](https://github.com/user-attachments/assets/c9fb7284-12ab-43f0-84af-654121368efc)

Because one of admins in the admin channel unbanned the person already, without clicking the Info button first, now it's impossible to debug why it triggered on this message.

Please either make the Info button not disappear, or just automatically show the info while unbanning

**Comment by umputun** [comment]
Currently, you can see all the info you are looking for in the log. 

Generally, I agree with the suggestion, and it would be nice if someone could prepare a PR addressing it.

**Comment by dsent** [comment]
> Currently, you can see all the info you are looking for in the log.
Where the detection info is logged, though? There's no such info in stdout, nor in the tg-spam.log. Is this DEBUG=true level info?

**Comment by umputun** [comment]
it is in the logs (container's log in this case). This iw what it looks like:

`2024/10/13 17:30:07.725 [DEBUG] {events/listener.go:300 events.(*TelegramListener).procEvents} ban initiated for {Text:this is spam: "батя" (1023634640) Send:true BanInterval:9600h0m0s User:{ID:1023634640 Username:bahtyaa DisplayName:батя} ChannelID:0 ReplyTo:568375 DeleteReplyTo:true CheckResults:[{Name:stopword Spam:false Details:not found} {Name:emoji Spam:true Details:72/2} {Name:images Spam:false Details:no images without text} {Name:cas Spam:false Details:record not found} {Name:multi-lingual Spam:false Details:0/5} {Name:similarity Spam:false Details:0.08/0.50} {Name:classifier Spam:true Details:probability of spam: 92.97%}]}`

**Comment by umputun** [comment]
on master, thx to @olitez 

@DarthGandalf you can try it with the :master image

**Comment by DarthGandalf** [comment]
Works, thanks!

I suspect that it won't work if the spam message itself happens to have 'original detection results' as substring though (haven't tested that)

**Comment by olitez** [comment]
@DarthGandalf yes but I don't think it make sense to fix (why spammer gonna use it?)
