### ISSUE TITLE
Add welcome messages

### ISSUE THREAD

**Issue by MissiaL** [umputun/tg-spam#127]
Thank you for your very cool project.

I would like to suggest adding the ability to send a welcome message to the general chat with the ability to delete it after a specified period of time. Is it possible to implement this?

**Comment by umputun** [comment]
Not sure what welcome message you meant, but the system already has an optional startup message. It is off by default, but you can set it to any text you like, and it will send it to the group as it starts. I don't see why this message should be deleted after a specified period of time.

If you meant a welcome message for a new user who joined the group, in this case, I don't see how this is related to the spam protection functionality this project is trying to provide.

**Comment by MissiaL** [comment]
I think you are right. Thank you for your project.
