### ISSUE TITLE
check for words for similar runes from different languages

### ISSUE THREAD

**Issue by freeseacher** [umputun/tg-spam#128]
Recently spammers stared to do mix runes from different alphabets. 
Lets add this as a check. 
mixing more than one alphabet in one word should has a bed smell.
this library should probably help 
https://pkg.go.dev/golang.org/x/text/unicode/norm

**Comment by umputun** [comment]
this rule already exists, see https://github.com/umputun/tg-spam/pull/106

this is from the reaadme.md:

---- 
Multi-language words

Using words that mix characters from multiple languages is a common spam technique. To detect such messages, the bot can check the message for the presence of such words. This option is disabled by default and can be enabled with the --multi-lang=, [$MULTI_LANG] parameter. Setting it to a number above 0 will enable this check, and the bot will mark the message as spam if it contains words with characters from more than one language in more than the specified number of words.
