### ISSUE TITLE
The bot bans if you attach several images with a signature

### ISSUE THREAD

**Issue by MissiaL** [umputun/tg-spam#137]
In Telegram you can group photos and sign them. For example, like this
![image](https://github.com/user-attachments/assets/8295b7ba-a717-4a5b-8bef-816abdaf9524)
If the user signs these photos, the bot will still ban him. This seems to be a bug

**Comment by umputun** [comment]
Without more details, it is impossible to diagnose. Probably, you have the images-only filter turned on, and those messages contain just images? Anyway, having a log and configuration will help.
