### ISSUE TITLE
OpenAI error: can't unmarshal response

### ISSUE THREAD

**Issue by dsent** [umputun/tg-spam#138]
For a lot of messages, OpenAI classification fails with this error:
``- openai: ham, OpenAI error: can't unmarshal response: invalid character '\`' looking for beginning of value``
It seems that the message contains backtick, but there are no backticks, nor monospace formatting in the messages in question (at least visible).
This (probably) makes the OpenAI veto option unfeasible, because a lot of spam messages get classified as ham by OpenAI processing.
What can possibly be the problem here?

**Comment by umputun** [comment]
log (with --dbg) may help to figure this out

**Comment by umputun** [comment]
#140 adds retry logic for OpenAI requests. By default, it is 1 (as before the change), but you can try to set it to a larger number. This is happening because some models may sometimes return invalid JSON responses. I have not seen it personally with GPT-4, but I have run into this a lot with simpler models, like 3.5.

Anyway, this is in the current master image; give it a try.

**Comment by dsent** [comment]
Will do and report the results here!

**Comment by dsent** [comment]
BTW, what is the logic for the OpenAI's veto power if there's an error processing the OpenAI request? Does it get ignored, or would it veto the spammer out of ban?

**Comment by umputun** [comment]
> OpenAI check is the last in the chain of checks. Unless --openai.veto is not set, the bot will not even call OpenAI if any of the previous checks marked the message as spam. However, if --openai.veto is set, it will be called and the message will be marked as spam only if OpenAI thinks so.

**Comment by dsent** [comment]
> OpenAI check is the last in the chain of checks. Unless --openai.veto is not set, the bot will not even call OpenAI if any of the previous checks marked the message as spam. However, if --openai.veto is set, it will be called and the message will be marked as spam only if OpenAI thinks so.
I've read this, but it's not clear what is the behavior in the following particular case:
1) OpenAI's veto is enabled.
2) The internal checks detect spam.
3) The message is sent to OpenAI to check if it vetoes the ban.
4) OpenAI request returns an error. In normal mode (veto=false) this results in message marked as ham just to be on the safe side. **But in case of veto processing, will the error be interpreted as "ham", thus, vetoing the "spam" classification already made by other checks?**

**Comment by umputun** [comment]
The whole idea of AI veto mode is to have it say the final yay/nay. Currently, the error is handled in a safe way, i.e., this will be identical to ham, and it won't allow other checks to set it to spam. I do agree we should treat the error as a third status (i.e., not available of some kind) and ignore the whole vetting thing in this case.

**Comment by umputun** [comment]
the change is on master, pls give it a try

**Comment by umputun** [comment]
released with [v1.14.0](https://github.com/umputun/tg-spam/releases/tag/v1.14.0)

**Comment by dsent** [comment]
Interestingly, when I modify the prompt requesting OpenAI to return a valid JSON, it starts giving `openai: OpenAI error: can't unmarshal response: invalid character '`' looking for beginning of value ` roughly 100% of the time. I can't figure out what's the problem, as the exact output of OpenAI is not written to debug output.

**Comment by dsent** [comment]
With the new debug into, there's some light in this issue: 
````
- openai: ham, OpenAI error: can't unmarshal response:
```json
{"spam":true, "reason":"The message contains a link to a bot for obtaining intimate photos, which is unrelated to mental health support.", "confidence":95}
``` - invalid character '`' looking for beginning of value
````
So, basically, GPT sometimes tries to format the JSON it generates as Markdown. Can probably be fixed by tweaking the prompt.

Will report my findings.

**Comment by dsent** [comment]
Adding this to the end of the prompt seems to help: `Return JSON only with no extra formatting!`.
No errors for 24h, but will observe the logs for some more time.

**Comment by dsent** [comment]
No "can't unmarshal" errors so far. The prompt modification seems to work well.

**Comment by umputun** [comment]
Thanks for digging deeper. I have added the suggested part to the default prompt.
