### ISSUE TITLE
Health checks endpoint

### ISSUE THREAD

**Issue by iamkarlson** [umputun/tg-spam#141]
It would be nice to introduce a health check endpoint so services like Cloud Run could use it and the whole deployment would be narrowed down to just run a single container there.

**Comment by umputun** [comment]
Currently, there is a `/ping` endpoint returning "pong" with a 200 status if the service is up. It doesn't check much, but the fact that the container is up and serving should be a close approximation to the real health check for now.

**Comment by iamkarlson** [comment]
Is it possible to enable this endpoint without enabling web server? I think that would solve the problem

**Comment by umputun** [comment]
Well, this is a part of the web server. I'm not sure why you don't want to just enable it. Just make sure you set the auth password, and it will be running all the endpoints. If you don't need to hit others, just ignore them?
