### ISSUE TITLE
Unable to open webpage menu

### ISSUE THREAD

**Issue by johnd0e** [umputun/tg-spam#144]
The problem occurs on both mobile devices and desktop computers when the navbar transforms into a 'hamburger' menu in a narrow window.

Unfortunately, the menu cannot be opened; only the icon is visible.

**Comment by johnd0e** [comment]
Did you forget to include bootstrap.min.js?

**Comment by umputun** [comment]
Indeed ;) I added it and also adjusted the `max-width` for small screens. The menu seems to be working now, and all pages, except for `detected_spam.html`, are resizing fine on small screens. I'm not sure how to deal with that wide table on the iPhone screen; it has way too many columns. I did not expect someone to use it on an iPhone and never designed it properly for small screens.

It is on master, give it a try.

**Comment by johnd0e** [comment]
Fixed, thanx!
