### ISSUE TITLE
Spam Filter Allows New Type of Spam

### ISSUE THREAD

**Issue by MissiaL** [umputun/tg-spam#160]
In the last two days, a message has been sent to the chat
![image](https://github.com/user-attachments/assets/5b75c6d6-1db5-4779-8e82-632a2acbc86b)
![image](https://github.com/user-attachments/assets/ddfff81d-69c1-4d91-85ef-545ec896a36f)
This message is not filtered in any way. Even if this message is sent to the admin filter chat

It turns out that this message is a story message.
![image](https://github.com/user-attachments/assets/62c198d4-93f3-4b1d-8bc3-d2664a659273)

I have logged this message:
```
tg-spam  | 2024/10/24 23:53:13.966 [DEBUG] {events/listener.go:271 events.(*TelegramListener).procEvents} {"message_id":237049,"from":{"id":8063614708,"first_name":"TON"},"date":1729803193,"chat":{"id":-1001366657637,"type":"supergroup","title":"ЖК life Варшавская","username":"LifeVarshavskaya","photo":null,"location":null},"message_auto_delete_timer_changed":null,"proximity_alert_triggered":null,"voice_chat_scheduled":null,"voice_chat_started":null,"voice_chat_ended":null,"voice_chat_participants_invited":null}
```
 Most likely, you do not have a filter set up for this type of message
 
 I can send you a sample of this message. If it's not too much trouble, write to me in telegram https://t.me/PetrAlexeev

**Comment by umputun** [comment]
have you tired to turn on "image-only" check?

`      --meta.image-only             enable image only check [$META_IMAGE_ONLY]`

**Comment by MissiaL** [comment]
Yes

**Comment by umputun** [comment]
Yes, and? I would guess it didn't help?

If this is the case, I would need some examples of those messages, as I have never seen them in real life and am not sure what all of this is about. Feel free to forward one of those to my TG (umputun).

**Comment by umputun** [comment]
@paskal any bright ideas? This message is somewhat different, but in the log line provided above, I see nothing that indicates it. The version of `github.com/go-telegram-bot-api/telegram-bot-api/v5` is the latest and greatest.

**Comment by dsent** [comment]
We started to get more and more spam consisting of videos in a circle (Telegram video messages).
Might make sense to add a check for video messages, and a check for audio messages, in a way similar to image-only check.

**Comment by mendelgusmao** [comment]
> @paskal any bright ideas? This message is somewhat different, but in the log line provided above, I see nothing that indicates it. The version of `github.com/go-telegram-bot-api/telegram-bot-api/v5` is the latest and greatest.

I'm guessing the current version of tbapi is not reading some extra fields that contain the data of this new kind of message

Debugging the payload directly from tbapi can probably provide some guidance

**Comment by paskal** [comment]
Maybe this one will do: https://github.com/OvyFlash/telegram-bot-api/blob/master/types.go#L556-L629

I'll look into adopting this library.

**Comment by dsent** [comment]
Enabling META_VIDEO_ONLY check doesn't stop circle videos from being sent.

**Comment by dsent** [comment]
Also, please see #176

**Comment by umputun** [comment]
> Maybe this one will do: https://github.com/OvyFlash/telegram-bot-api/blob/master/types.go#L556-L629
> 
> I'll look into adopting this library.

This fork is conceptually close to the original code, but it is not compatible on multiple levels. I have tried to adopt it, and it seems possible; however, all the parts communicating with this library should be carefully adjusted.

**Comment by umputun** [comment]
@paskal what do you think about forking the lib and adding new types of messages without breaking compatibility? To me it sounds like a simplest solution

**Comment by paskal** [comment]
I've seen too many abandoned Telegram libraries for go the path creating another one. Today it's stories and tomorrow with the new API release it would be something else: I would prefer just staying on some up-to-date library.

Let me give migration a try.

**Comment by negasus** [comment]
I try to keep my library always up to date. You can try https://github.com/go-telegram/bot ;)

**Comment by paskal** [comment]
https://github.com/umputun/tg-spam/pull/180 switches to https://github.com/OvyFlash/telegram-bot-api/, it will be merged soon.
Does someone want to follow it up and add detection for the new type of spam?

**Comment by umputun** [comment]
after the last merge the detection should be working as a part of video-only meta-check
