### ISSUE TITLE
[Suggestion] Log more OpenAI results with --dbg

### ISSUE THREAD

**Issue by dsent** [umputun/tg-spam#162]
Firstly, right now, the results of OpenAI requests are **not logged** if the message is eventually classified as ham. It'd be useful to log them in any case.
Secondly, it'd be useful to log **full raw output of OpenAI** requests when --dbg is enabled.

This could help debug and resolve OpenAI-related issues.
A couple of other issues (#138 and #139), are not actually fully resolved, but further investigation is hard without this kind of extra debug info.

**Comment by umputun** [comment]
I have added the original response from OpenAI to the details in case decoding failed. I don't think we need an extra debug print for this, as the results would be in the details of a check we are already printing out in debug mode.

**Comment by dsent** [comment]
What about the first issue mentioned? Right now I don't see OpenAI's response in the log in case it's successful, and the message is deemed not spam:
`[DEBUG] {bot/spam.go:104 bot.(*SpamFilter).OnMessage} user ** is not a spammer, {name: stopword, spam: false, details: not found}, {name: images, spam: false, details: no images without text}, {name: cas, spam: false, details: record not found}, {name: similarity, spam: false, details: 0.10/0.50}, {name: classifier, spam: false, details: probability of ham: 100.00%}`

**Comment by umputun** [comment]
should be on master
