### ISSUE TITLE
[Feature request]  Add only video messages check

### ISSUE THREAD

**Issue by BorisOsipov** [umputun/tg-spam#165]
I've been getting an increasing amount of spam in the form of only circular video messages (Telegram video messages) with action button. It will be nice to add a filter for video messages similar to the existing image-only check.

Example JSON dump from such spam https://gist.github.com/BorisOsipov/1fc255568988f25e7aa68768c9704d06

**Comment by umputun** [comment]
Thanks for the report. I have added a new meta-check for video messages and video notes.

```
--meta.video-only             enable video only check [$META_VIDEO_ONLY]
```

The updated version is in the master image. Please give it a try and see if it fixes your issue.

**Comment by BorisOsipov** [comment]
Thanks for the fix. I've updated my bot instance\config to the master image and will check it

**Comment by BorisOsipov** [comment]
We haven’t received any more video spam samples. It seems spammers didn’t get enough traffic from this type of spam version.
