### ISSUE TITLE
Images only check ignores the whitelist

### ISSUE THREAD

**Issue by dsent** [umputun/tg-spam#167]
After enabling the images only check, we noticed that normal users, who were already in the white list, were banned by the bot after sending images without text. I believe this to be unintended behavior.

**Comment by umputun** [comment]
From the code, I don't see how this is even possible. The check for approved users happens before any other checks are reached, including the image-only check (a part of the meta checks).

https://github.com/umputun/tg-spam/blob/fd75fc789e09ff89b93567d7aa934d2e77bd6bda/lib/tgspam/detector.go#L120-L120

Are you sure you have not set `ParanoidMode` (check all messages, env: 'PARANOID', cli: '--paranoid')? The other way to have the check invoked for active users is by setting `FIRST_MESSAGES_COUNT`, which is by default 1 ("number of first messages to check").

**Comment by dsent** [comment]
I was able to reproduce. If you're okay with that, I can follow the logs to you privately (they contain some sensitive data). But my user was indeed banned by the bot while being in the whitelist (and, in fact, remaining in the whitelist after the ban).

**Comment by dsent** [comment]
And the reasons for the ban were:
![image](https://github.com/user-attachments/assets/8d635718-86b5-41a6-8033-fb7d2aa770a3)

**Comment by umputun** [comment]
> I was able to reproduce. If you're okay with that, I can forward the logs to you privately (they contain some sensitive data). But my user was indeed banned by the bot while being in the whitelist (and, in fact, remaining in the whitelist after the ban).

sure, send it over. also configuration (docker compose or cli params) may help to reproduce it locally

**Comment by umputun** [comment]
should be fine on master, pls give it a try. the PR #177 explains what the issue was.

**Comment by umputun** [comment]
By the way, thanks for providing details and pushing the issue, which was real.
