### ISSUE TITLE
Ignore invisible zero-sized chars in messages 

### ISSUE THREAD

**Issue by asm0dey** [umputun/tg-spam#169]
I have a few interesting messages in my spam list
```
D<2062>ude i<2062>t i<2062>s t<2062>he la<2062>st da<2062>y t<2062>his eve<2062>nt is l<2062>ive so qu<2062>ickly take one https://uven.xyz/?claim=16479
Р<2062>ебята д<2062>авайте б<2062>ыстрее з<2062>аберите с<2062>обытие с<2062>коро з<2062>аканчивается https://ulid.xyz/?ClaimReward=12484
F<2068>ast t<2068>a<2068>ke i<2068>t no<2068>w https://pohy.xyz/
```

It seems spammer use invisible chars now, probably it makes sense to ignore them altogether

**Comment by asm0dey** [comment]
Actually it's a sign for classifier, I think, isn't it?

**Comment by umputun** [comment]
> Actually it's a sign for classifier, I think, isn't it?

If you mean what those characters are helpful for in the classifier in some way, I don't think so. The classifier deals with tokens that are randomized by the presence of all those characters, and stripping those before the tokenization should improve the accuracy for the classifier.

**Comment by paskal** [comment]
I think "there is a presence of strange symbols in the input" might give a good spam signal.

**Comment by umputun** [comment]
> "There is a presence of strange symbols in the input" might give a good spam signal.

This could be a signal for some heuristic-based checker, similar to the emoji count one we have, but unlikely to be a good/useful signal for the classifier checker. I'm not sure if there is an actual need for this new checker, as I have yet to see such examples of spam in the wild.

**Comment by asm0dey** [comment]
Have them in my dynamic spam :)

**Comment by umputun** [comment]
> Have them in my dynamic spam :)

I believe you, and probably it will be more popular someday. The same story was with the multi-language checker - first, it was reported as an occasional thing, but later it became very common and warranted a dedicated checker.

I think cleaning those suckers, as I did, should help with detection, as it will be properly processed by the classifier, stop-words, and similarity checkers. If you see it doesn't help, please let me know, and we will see what the next step is.
