### ISSUE TITLE
issues with running latest v.1.3.1 bot

### ISSUE THREAD

**Issue by slawiko** [umputun/tg-spam#32]
I'm receiving the following failure:

```
tg-spam v1.3.1-e9aa206-20231222T15:42:53
2023/12/23 19:10:18.341 [ERROR] can't make data db, unable to open database file: out of memory (14)
2023/12/23 19:10:18.341 [ERROR] can't make data db, unable to open database file: out of memory (14)
>>> stack trace:
main.main()
	/build/app/main.go:139 +0x465
```

for the following run command:

`docker run ghcr.io/umputun/tg-spam:v1.3.1 --telegram.token=*** --telegram.group=*** --admin.group=*** --telegram.preserve-unbanned --no-spam-reply --max-emoji=-1`

If I run from locally built go binary, everything is fine. Also, everything is fine if I run from locally built docker image.

What am I doing wrong?

**Comment by umputun** [comment]
This is a permission issue related to the base image,  in case you run the container without mounting the location of the dynamic files. I have no idea why this can be intentional, and strictly speaking, failing int this case may be a decent reaction; however, the message from SQLite with "out of memory" is confusing. 

I have added better diagnostics and checks. Now, it will show a warning if you run it like this, without mounting volume, but it will continue to work with disabled dynamic ham/spam files. I wonder why this can be useful for you unless it was a mistake.

> if I run from locally built go binary, everything is fine.

Locally, it has no issue making a directory with proper permissions, so this is expected to run.

> Also, everything is fine if I run from locally built docker image.

This is most likely because, after your local run, it made tg-spam.db in your data/ and your build with this. I have added this file to .dockerignore to make the image build more consistent.

**Comment by slawiko** [comment]
> I wonder why this can be useful for you unless it was a mistake

well, you're right it is not useful. I used to run it like that:

```docker run -d -v /root/data:/dynamic ghcr.io/umputun/tg-spam:v1.2.5 --telegram.token=*** --telegram.group=*** --admin.group=*** --no-spam-reply --files.approved-users=/dynamic/approved-users.txt --files.dynamic-spam=/dynamic/spam.txt --files.dynamic-ham=/dynamic/ham.txt```

but when I upgraded on 1.3.1 and started to receive error, I tried to debug it and play a bit with run configuration, simplified it and so on.

Thanks for detailed analysis!

Everything is working fine if I run this way:

```
docker volume create dynamic-tg-spam
docker run -v dynamic-tg-spam:/srv/data -d ghcr.io/umputun/tg-spam:v1.4.1 --telegram.token=*** --telegram.group=*** --admin.group=*** --telegram.preserve-unbanned --no-spam-reply --max-emoji=-1
```

however logs contain line `[WARN]  dynamic files dir "/srv/data" is not mounted, changes will be lost on container restart` cause folder still contains `.not_mounted` file.

**Comment by umputun** [comment]
this is interesting. Apperently if the volume is empty docker copy all the files what was on the same mount points. This is surprising behavior, I expected it to work similar to the direct host volume mount, i.e. -v /blah/data:/srv/data which will override /srv/data without trying to be cute and helpful.

From what I understood, this happens only in case if your volume is empty, so doing smth like `docker run -it --rm -v dynamic-tg-spam:/data alpine touch /data/.keep` on freshly created volume will prevent it.  Alternatively, you may create a second volume for dynamic files only and pass it with --files.dynamic. This will be also better config if you use (or planning to use) updater part of tg-spam

_Saying all of this - I do agree what the current behavior is confusing and even wrong. In your case, `/srv/data` is mounted, but I don't know how to detect it without relaying on the presence of that `.not_mounted` and without adding docker support into container/bot. If you have any bright ideas how to make it right - pls let me know_

**Comment by umputun** [comment]
the current master should handle it better. This is not the nicest solution and not something to write home about, but seem to work fine.  


<img width="1198" alt="image" src="https://github.com/umputun/tg-spam/assets/535880/369f11a1-a609-4727-a7cb-19d6d9d56f27">

**Comment by slawiko** [comment]
looks and works good. Thanks!
