### ISSUE TITLE
Problem with spam messages containing pictures

### ISSUE THREAD

**Issue by alehano** [umputun/tg-spam#47]
Today I had one case when the bot didn't  delete spam message forwarded to a admin group. I'm not sure is it training mode specific problem or general.
Looks like the bot didn't get the message text.
Sha256 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is empty string.

Here is logs:

```
2023/12/28 09:03:24.411 [DEBUG] {events/listener.go:238 events.(*TelegramListener).isAdminChat} message in admin chat -4058117643, from pretty_friend
2023/12/28 09:03:24.411 [DEBUG] {events/admin.go:58 events.(*admin).MsgHandler} message from admin chat: msg id: 401, update id: 84145103, from: pretty_friend, sender: ""
2023/12/28 09:03:24.411 [DEBUG] {events/admin.go:69 events.(*admin).MsgHandler} forwarded message from superuser "pretty_friend" to admin chat -4058117643: ""
2023/12/28 09:03:24.412 [DEBUG] {storage/locator.go:131 storage.(*Locator).Message} failed to find message by hash "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855": sql: no rows in result set
2023/12/28 09:03:24.412 [WARN]  {events/listener.go:115 events.(*TelegramListener).Do} failed to process admin chat message: not found "" in locator
2023/12/28 09:03:24.413 [DEBUG] {events/listener.go:272 events.(*TelegramListener).sendBotResponse} bot response - error: not found "" in locator, reply-to:0
```
Here is the message, maybe it will be useful for a test case:

```
💎🎄ГОTОВЬСЯ K HOBОMУ ΓOДᎩ С НОBЫМ ДОХОДOМ🎄💎

❗️𝖬ecтa огрaничeны❗️ 

💰Πpисoединяйcя к нaш𝚎й кoманде в сф𝚎p𝚎 цифpoвых активоⲃ💰

🔥Тeбя ждет нoвoe интереcнoе нaпpaⲃлeние, пacивный yдaл𝚎нный доxoд oт 10 000 ₽₽₽/день, и бecплaтноe обyчeние🧑‍💻💸

Bcё, чтo нyжнo – вoзpаcт от 18 л𝚎т, смаpтфон и 1-2 часа ⲃремени ⲃ день
❗️Всe л𝚎гально и б𝚎з пр𝚎доплaт❗️

Давaй встречать Нoвый гoд c увеpеннocтью ⲃ cвоем Փинaнcовом yспехe! 💰🚀

‼️Пиши напрямyю pукоⲃодителю 👉 @ser______ratov
```

Here is how it looks like:
<img width="250" alt="Screenshot 2023-12-28 at 09 30 34" src="https://github.com/umputun/tg-spam/assets/1269330/5c44d0da-1fc7-48a1-9e51-2c608ab8e0ab">

I suppose it can be because of a picture. As I know Telegram sends a picture as a separate message and then glue it together with a text.

_Originally posted by @alehano in https://github.com/umputun/tg-spam/issues/17#issuecomment-1870986248_
            

UPD: Today I had the second case after forwarding a message to an admin group.

<img width="400" alt="Screenshot 2024-01-02 at 12 37 36" src="https://user-images.githubusercontent.com/1269330/293694425-d22a433e-2230-424e-8a4c-bb4e7f7f289b.png">

**Comment by umputun** [comment]
Such messages don't have Text filed populaded but rather consider it as a Capture for the image. This is a strange thing, but whatever. 

I have added support for this, and now the image's capture should be populated as normal text inside the handlers. I have made an image from that branch, pls try `umputun/tg-spam:pic` image and see if it solves the problem. I had no time to test if everywhere, but I confirmed the caption is passing along in the main event loop as well in admin forwards

**Comment by alehano** [comment]
It seems something wrong with this version. After forwarding messages into admin group I got errors:

```
error: 2 errors occurred:
  failed to remove user 6403583972 from approved list: failed to delete approved user from storage: failed to delete approved user 6403583972 from storage: failed to get approved user for id 6403583972: sql: no rows in result set
  failed to delete message 518323: Bad Request: message to delete not found
```

**Comment by umputun** [comment]
I don't see how this is even related. To me, it looks like your tg-spam.db cleared or smth like this

**Comment by alehano** [comment]
It's weird. I didn't close look what happening, but after rolling back to master version error messages disappeared.
