### ISSUE TITLE
Controversial results on a spam message

### ISSUE THREAD

**Issue by asm0dey** [umputun/tg-spam#53]
![Screenshot_20240122-000133](https://github.com/umputun/tg-spam/assets/1297282/0d736b71-ad79-40ec-ac58-93f76bed754d)

It's one message, but not reported yet messages: one that it's spam, second that it's ok

**Comment by umputun** [comment]
The second message didn't pass the length check, and the first did. My guess - the first message was actually longer and trimmed (spaces eliminated) or smth like this. Maybe params were changed between them (`min-msg-len`)?  It is hard to tell,   without checking the logs - you should see how it sees the messages, and it will likely help to figure this out.

_The min size of a message can be changed to whatever length you like in cli/enn. The original reason to filter out short messages is to prevent false-positives based on insufficient info, for example, it makes no sense to check a message like "Hello" or smth like this_

**Comment by umputun** [comment]
upd: I have addressed the issue with incorrect score detection of the forwarded spam. I think this was the reason.
