### ISSUE TITLE
Deletion of spam sample duplicates

### ISSUE THREAD

**Issue by glebsterx** [umputun/tg-spam#63]
If in the admin chat you confirm the ban of users who write the same messages, such messages are added twice. And when you try to remove a duplicate from the sample database, both messages (both lines) are deleted. This is not a problem if you remember this - it is a nuance of placing the sample database in a text file.

Я перейду на русский если автор не против.
Предложил бы хранить семплы как-то по-другому, но идей кроме файловой базы у меня нет.. Да и не шарю я в этом вашем Golang
Честно говоря думаю автор не рассчитывал, что образцов спама будет так много =)
Возможно стоит в будущем предусмотреть какую-то очистку базы от дубликатов, либо проверку на существование идентичной записи при добавлении. Потому что невозможно вспомнить -- что уже было, а что нет.
Спасибо за внимание =)

**Comment by umputun** [comment]
yeah, the proper solution would be to add a check if the same message already in samples and don't add it for the second time.

**Comment by glebsterx** [comment]
Thanks a lot!

**Comment by umputun** [comment]
the fix in place, released as a part of v1.11.1 hotfix
