### ISSUE TITLE
Soft ban mode not working for my

### ISSUE THREAD

**Issue by AdAvAn** [umputun/tg-spam#75]
I'm trying to use the Soft ban functionality, it is critical for me.
I write a phrase from the stop-words.txt dictionary in my test chat, but the bot does not restrict me, but bans me and removes me from the chat.

What's my mistake?

I'm using v1.12.0 here is the container configuration:

```
services:
  tg-spam:
    image: umputun/tg-spam:latest # use :master tag for latest (unstable) version
    hostname: tg-spam
    restart: always
    container_name: tg-spam
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TELEGRAM_TOKEN=000000Q
      - TELEGRAM_GROUP=-00000
      - TZ=Europe/Sofia          
      - ADMIN_GROUP=-000000  
      - LOGGER_ENABLED=true      
      - LOGGER_FILE=/srv/logs/tg-spam.log
      - LOGGER_MAX_SIZE=5M      
      - FIRST_MESSAGES_COUNT=4   
      - META_IMAGE_ONLY=true     
      - META_LINKS_ONLY=true     
      - MAX_EMOJI=-1             
      - NO_SPAM_REPLY=false      
      - SERVER_ENABLED=false      
      - NO_SPAM_REPLY=true
      - SOFT_BAN=true
      - DEBUG=true 			 
      - DRY=false
      - PARANOID=true
      - TRAINING=false
    volumes:
      - /telegram/tg-spam/data/:/srv/data      
      - /telegram/tg-spam/logs/:/srv/logs      
```

Potentially, the problem is that in [main.go,](app/main.go) the `TelegramListener` structure does not initialize the `SoftBanMode` parameter from the options strcut.

**Comment by umputun** [comment]
Your config is fine, it was me who missed one of the commits. I've pushed the changes and tagged it as v1.12.1.

**Comment by AdAvAn** [comment]
Great, in version v1.12.1 it works as described, only a limitation.

There is also a nuance that I noticed: if I respond to a message marked spam or /spam, then the user is not limited, remove him from the group as before.
It would be great that if Soft ban is enabled, then when the user is marked as spam, the user is blocked instead of deleted.

**Comment by AdAvAn** [comment]
When spam is detected, I receive a message in the administrator chat (`--admin.group`) with the text:

"_permanently banned {0000000 Clean_Fonk Good man}_", but I use the parameter (`--soft-ban`), and the user is not banned, his access to functions is restricted, it would be more logical to write a message like "_permanently restricted {0000000 Clean_Fonk Good man}_" .

But this is not significant.

**Comment by AdAvAn** [comment]
Thanks for the quick update.
Your logic regarding the ban looks logical, if the administrator sends a ban, then he does it consciously and the user leaves the chat.
Thanks for the clarifications.
