### ISSUE TITLE
Unable to properly ban spam via official(?) Channel_Bot 

### ISSUE THREAD

**Issue by BorisOsipov** [umputun/tg-spam#77]
I've run into spam attack via `Channel_Bot`. The `tg-spam` can't properly ban users that post the messages. It seems `tg-spam` tries to ban `Channel_Bot` `"id":136817688`, but the culprit is the user that somehow abuse it. 

[See logs ](https://pastebin.com/KC0mvauX)

The spam-bot admin group is spammed with unsuccessful attempts to ban `Channel_Bot` but not the culprits.

![image](https://github.com/umputun/tg-spam/assets/6514276/84b643f0-92b4-4496-936a-968bf65d8bbc)

**Comment by umputun** [comment]
As far as I know, there is no way to see the real user behind the channel or ban the channel this way. I'd suggest disabling channels from joining. I'm not sure if this can be done with Telegram itself, but there are bots that can do this.

If you have a better idea on how to identify such a user, please share it.

**Comment by BorisOsipov** [comment]
>If you have a better idea on how to identify such a user, please share it.

Thank you for your reply. I don't know how to stop this spam either. Then let's close the issue.
