### ISSUE TITLE
Add the ability to delete the system message about joining a group

### ISSUE THREAD

**Issue by umputun** [umputun/tg-spam#92]
### Discussed in https://github.com/umputun/tg-spam/discussions/91

<div type='discussions-op-text'>

<sup>Originally posted by **fear-rus** June  3, 2024</sup>
I suggest adding the ability to delete the system message about joining the group after deleting the message and banning the user. When there is a lot of spam, and the bot deletes it, then there are system messages about joining, which look like spam pages in the group. Is it possible to automatically delete messages about joining a group of spambots that have been deleted?</div>

**Comment by ninedraft** [comment]
Yes, it's totally possible with right admin rights for bot to delete such messages. Do you want to delete **all** "user X joined" messages or only spamers? In the second case I think bot need some KV user-id -> user-joined-messsage-ID storage. 

This feature seems to be quite simple. If you don't mind, I can take it for implementation

**Comment by umputun** [comment]
> Do you want to delete all "user X joined" messages or only spamers? In the second case I think bot need some KV user-id -> user-joined-messsage-ID storage.

yes, this is the intent. The bot already has a store (sqlite) and you can either add just another table, or update storage.Locator to handle join messages.

**Comment by coperius** [comment]
Whether to delete messages about removing a user from a group?
